default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: listless

development:
  <<: *default
  database: listless_development
test:
  <<: *default
  database: listless_test
