# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

development:
  <<: *default
  secret_key_base: ac49f513d444fcdb4da438c14606a0da586080f2030ab2f12349a0128fa60a6bfae6466c5f94308c405b97ec70faa9ec902c74813a439a50c81e272f8e892d35

test:
  <<: *default
  secret_key_base: ac49f513d444fcdb4da438c14606a0da586080f2030ab2f12349a0128fa60a6bfae6466c5f94308c405b97ec70faa9ec902c74813a439a50c81e272f8e892d35
  secret_key_base: 3ad510dafe223a87b7db4fc39778edf17b4b2db1553bfe7caf3f039b46d3ad926ea73fd32cb07106fdf04d8e5618b98c843fe8a44ff9c66d4fd2302b45366665

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: ac49f513d444fcdb4da438c14606a0da586080f2030ab2f12349a0128fa60a6bfae6466c5f94308c405b97ec70faa9ec902c74813a439a50c81e272f8e892d35
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
